name: tabumium
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # state
  flutter_bloc: ^9.0.0

  # cache
  shared_preferences: ^2.5.3

  # design
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.2
  

  # services
  package_info_plus: ^9.0.0
  audioplayers: ^6.5.1
  vibration: ^3.1.4
  http: ^1.2.2
  url_launcher: ^6.3.1

  # security
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # hive_generator: ^2.0.1
  build_runner: ^2.10.2

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/appbars/
    - assets/images/backgrounds/
    - assets/images/buttons/
    - assets/images/categories/
    - assets/images/icons/
    - assets/audio/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-SemiBold.ttf
          weight: 600
